version: '3.1'

services:
  mysql:
    image: mysql:8
    container_name: mysql_clinica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
